### ISSUE TITLE
My Notes Page

### ISSUE THREAD

**Issue by rwespey** [fengxia41103/stock#6]
According to the documentation, When I add a note from the My Notes page, the note is considered to be a General note.  A couple of issues:

- If this is a general note, why am I being asked to predict how the stock will perform?  That should only be available if I add a stock-specific note.
- From this page, it would be nice to allow me to assign the note to a specific stock.  This way I can record thoughts today and then assign those thoughts to a stock if I add the stock later.

**Comment by fengxia41103** [comment]
See 2e9823e

- There was a bug fix in this commit in the Diary creation API whereas `stock` should be the stock ID, but was given the resource URI. This was the cause that note creation was failing.
- Refactored stock detail actions to a dropdown, including creating new note, which is now a dialog.
- Stock specific note can be created using this menu. Upon saving successful, it will redirect to the Notes list page.
- When creating stock specific note, if the stock symbol is not mentioned in the content, it will be added to content automatically. This is needed because notes for a stock is filtered by backend using content and stock symbol. For example, on MSFT detail page, it will search through all notes whose content includes the word "MSFT". Therefore, even if the note is linked to MSFT, filter will fail if content doesn't include MSFT. This commit will now ensure the symbol is always part of the content.

**Comment by rwespey** [comment]
Sweet!
